version: '3.1'
services:
    postgres:
        image: 'postgres:11.1-alpine'
        working_dir: /var/www/html
        volumes:
            - '..:/var/www/html'
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
        ports:
            - '${POSTGRES_PORT}:5432'

    nginx:
        image: 'nginx:alpine'
        working_dir: /var/www/html
        volumes:
            - '..:/var/www/html'
            - './build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './log/nginx:/var/log/nginx'
        ports:
            - "${NGINX_PORT_HTTP}:80"
            - "${NGINX_PORT_HTTPS}:443"

    php:
        build: build/php-fpm
        working_dir: /var/www/html
        volumes:
            - '..:/var/www/html'
            - './build/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
